### ISSUE TITLE
Misbehaving Coinscope-GH:0.2

### ISSUE THREAD

**Issue by oriste** [jameslitton/coinscope#1]
Getting massive amounts of connects from IP 72.36.89.11 with this identification string, all from different ports, and they all result in the following errors in the log file:

2017-04-08 09:16:34 Misbehaving: 72.36.89.11:nnnnn peer=mmmmm (0 -> 1)
2017-04-08 09:16:34 ProcessMessages(addr, 35 bytes) FAILED peer=mmmmm
2017-04-08 09:16:35 version handshake timeout from mmmmm

**Comment by jameslitton** [comment]
If I understand you correctly, you're running a bitcoin node and receiving connections from 72.36.89.11 (UIUC) that is not completing a proper handshake with your node. 

I'm sorry you're having this trouble. Coinscope is software that was originally written to connect to bitcoin based cryptocurrency nodes in order to measure certain aspects of their networks. The code is publicly available and of course I have no direct control over how it is used (correctly or not), nor ability to handle abuse complaints. In this case I'd guess that the machine is a bit overloaded (the horde branch may help) and is not keeping up with all of its handshake attempts.

I attempted to visit http://72.36.89.11 to see if a webpage with contact information is available, but since there isn't, the abuse contact for that ip address is abuse@uiuc.edu. It's possible that this is actually a result of some ongoing experiments Andrew Miller is running there (http://soc1024.ece.illinois.edu/). If so, you may get more immediate help by contacting him directly. The software does support an IP address blocklist that you can be put on, and I'm sure he'd want to know if his experiment is disrupting the network in any way.

Best of luck.
