### ISSUE TITLE
Issue : limit too low, aborting (1024)

### ISSUE THREAD

**Issue by varun-v-deshpande** [jameslitton/coinscope#4]
Hello,

I am new to coinscope. I want to retest the results from your research paper. However I do not know how can I map Bitcoin's connection topology.  Could you please guide me with that ?

Also, when I run connector, It gives following error 
`
$:~/coinscope/connector$ ./main 
limit too low, aborting (1024)
`

**Comment by jameslitton** [comment]
You're getting this error because you are launching the program in an environment where it can only open 1024 files/sockets. This is not enough to interact with a large proportion of the bitcoin network, so it aborts.

It's meant to save you from wasting time and having to kill it later. Take a look at ulimit.

The paper describes the algorithms we used to map the network. I don't think getaddr will work on the current network anymore. There is some software in the clients directory that performs some of the probing, but not the analysis itself.
